package com.howbig.riot.type.item;

/**
 * Created by Alex on 5/21/2014.
 */
public class ItemStats {
   public double FlatHPPoolMod;
    public double rFlatHPModPerLevel;
    public double FlatMPPoolMod;
    public double rFlatMPModPerLevel;
    public double PercentHPPoolMod;
    public double PercentMPPoolMod;
    public double FlatHPRegenMod;
    public double rFlatHPRegenModPerLevel;
    public double PercentHPRegenMod;
    public double FlatMPRegenMod;
    public double rFlatMpRegenModPerLevel;
    public double PercentMPRegenMod;
    public  double FlatArmorMod;
    public double rFlatArmorModPerLevel;
    public  double PercentArmorMod;
    public double rFlatArmorPenetrationMod;
    public double rFlatArmorPenetrationModPerLevel;
    public  double rPercentArmorPenetrationMod;
    public double rPercentArmorPenetrationModPerLevel;
    public double FlatPhysicalDamageMod;
    public double rFlatPhysicalDamageModPerLevel;
    public  double PercentPhysicalDamageMod;
    public  double FlatMagicDamageMod;
    public double rFlatMagicDamageModPerLevel;
    public double PercentMagicDamageMod;
    public double FlatMovementSpeedMod;
    public  double rFlatMovementSpeedModPerLevel;
    public double PercentMovementSpeedMod;
    public double rPercentMovementSpeedModPerLevel;
    public double FlatAttackSpeedMod;
    public double PercentAttackSpeedMod;
    public double rPercentAttackSpeedModPerLevel;
    public double rFlatDodgeMod;
    public double rFlatDodgeModPerLevel;
    public double PercentDodgeMod;
    public double FlatCritChanceMod;
    public double  rFlatCritChanceModPerLevel;
    public double PercentCritChanceMod;
    public double FlatCritDamageMod;
    public double rFlatCritDamageModPerLevel;
    public double PercentCritDamageMod;
    public  double FlatBlockMod;
    public double PercentBlockMod;
    public double FlatSpellBlockMod;
    public double rFlatSpellBlockModPerLevel;
    public  double PercentSpellBlockMod;
    public  double FlatEXPBonus;
    public  double PercentEXPBonus;
    public double rPercentCoolDownMod;
    public double rPercentCoolDownModPerLevel;
    public double rFlatTimeDeadMod;
    public double rFlatTimeDeadModPerLevel;
    public double rPercentTimeDeadMod;
    public double rPercentTimeDeadModPerLevel;
    public double rFlatGoldPer10Mod;
    public double rFlatMagicPenetrationMod;
    public  double rFlatMagicPenetrationModPerLevel;
    public  double rPercentMagicPenetrationMod;
    public double rPercentMagicPenetrationModPerLevel;
    public  double FlatEnergyRegenMod;
    public double rFlatEnergyRegenModPerLevel;
    public  double FlatEnergyPoolMod;
    public double rFlatEnergyPoolModPerLevel;
    public  double PercentLifeStealMod;
    public double PercentSpellVampMod;
}
